browser=chrome
headless=false
code=123
BASEURL = https://opensource-demo.orangehrmlive.com

datasource_url=jdbc:mysql://localhost:3306/orangehrm
datasource_username=root
datasource_password=123456

#View Port
web.viewport.width=1920
web.viewport.height=1080

