browser=chrome
headless=false

BASEURL = http://localhost:4200/login
LOGINURL = http://localhost:8080/login
DASHBOARDURL = http://localhost:8080/dashboard

TAKE_SCREENSHOT=true

code = nrx0D4xRpVLHXQe4WWW8bAkI1pI2RBuKrxcUnJU3VC7IgSAnNxZYmql8lSpDNsdNG434-cSTgWzxGZw212UkJH7OFKm0TX-SPDdcv6P15h7FQFghkZcSXkknHrUPQBCZ
#  datasource_url=jdbc:mysql://localhost:3306/crm_db?useUnicode=true&characterEncoding=UTF-8&nullDatabaseMeansCurrent=true&databaseTerm=SCHEMA
#  datasource_username=root
#  datasource_password=root125p

#View Port
web.viewport.width=1920
web.viewport.height=1080

datasource_url=jdbc:mysql://localhost:3306/crm_db?useUnicode=true&characterEncoding=UTF-8&nullDatabaseMeansCurrent=true&databaseTerm=SCHEMA
datasource_username=root
datasource_password=1104

username_admin=jdoe
password_admin=123456

username_user=jsmith
password_user=123456


